default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: <%= ENV.fetch("DEV_DB_NAME") %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB_NAME") %>

production:
  <<: *default
  database: <%= ENV.fetch("PROD_DB_NAME") %>
